version: "2.4"

services:

  prometheus:
    image: quay.io/prometheus/prometheus:v2.37.0
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /data/prometheus/:/prometheus/
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=2h
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.config.file=/etc/prometheus/web.yml
      - --web.enable-admin-api
      - --web.enable-lifecycle
    links:
      - alertmanager:alertmanager
    restart: always

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.28.0
    container_name: thanos-sidecar
    user: root
    ports:
      - 10901:10901
      - 10902:10902
    volumes:
      - ./thanos/:/etc/thanos/
      - /data/prometheus:/prometheus/
    command:
      - sidecar
      - --prometheus.url=prometheus:9090
      - objstore.config-file=/etc/thanos/oss.yaml
      - --tsdb.path=/prometheus/
    links:
      - prometheus:prometheus

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.24.0
    container_name: alertmanager
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - /data/alertmanager/:/alertmanager/
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.config.file=/etc/alertmanager/web.yml
    links:
      - prometheus-webhook-dingtalk:prometheus-webhook-dingtalk
    restart: always
  
  prometheus-webhook-dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: prometheus-webhook-dingtalk
    ports:
      - 127.0.0.1:8060:8060
    volumes:
      - ./prometheus-webhook-dingtalk:/etc/prometheus-webhook-dingtalk/
    command:
      - --config.file=/etc/prometheus-webhook-dingtalk/config.yml
      - --web.enable-lifecycle
    restart: always
